services:
  middleware:
    image: cawi12345/middleware:latest
    container_name: middleware
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - stack.env
    volumes:
      - middleware_uploads:/app/uploads

volumes:
  middleware_uploads:
